import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { baseFont } from "./ui/fonts";
import Container from "@mui/material/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baseFont.className} antialiased`}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
