var FLAWS_LIST = [
    {'flaw_type': 'Story', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Abandoned Apprentice', 'pages': '12'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Ability Block', 'pages': '51'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Afflicted Tongue', 'pages': '51'},
    {'flaw_type': 'Supernatural', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Age Quickly', 'pages': '51'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Age Quickly [2]', 'pages': '47'},
    {'flaw_type': 'Social', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Amazonian Slave', 'pages': '19'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Ambitious', 'pages': '51'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Ambitious [2]', 'pages': '51'},
    {'flaw_type': 'General', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Anchored to the (Land)', 'pages': '47'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Divine', magnitude: 'Minor', points: 1, 'name': 'Apostate', 'pages': '36'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Arthritis', 'pages': '51'},
    {'flaw_type': 'Hermetic', 'book': 'The Mysteries, Revised Edition', magnitude: 'Minor', points: 1, 'name': '(Astrological) Cyclic Magic (negative) ', 'pages': '37'},
    {'flaw_type': 'Special', 'book': 'The Mysteries, Revised Edition', 'magnitude': '*', 'name': '(Astrological) Mutable (Flaw)', 'pages': '37-38 '},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Avaricious', 'pages': '51'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Avaricious [2]', 'pages': '51'},
    {'flaw_type': 'Story', 'book': 'Grogs', magnitude: 'Major', points: 3, 'name': 'A Deal with the Devil', 'pages': '78'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Baneful Circumstances', 'pages': '47'},
    {'flaw_type': 'Social', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Bastard', 'pages': '9'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Societates', magnitude: 'Minor', points: 1, 'name': 'Beloved Rival', 'pages': '94'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Minor', points: 1, 'name': 'Beloved Slave', 'pages': '19'},
    {'flaw_type': 'Story', 'book': 'City & Guild', magnitude: 'Major', points: 3, 'name': 'Bigamist', 'pages': '109'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Bitter Mistress', 'pages': '19'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Blackmail', 'pages': '51'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Black Sheep', 'pages': '51'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Blatant Gift', 'pages': '51, 75 '},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Blatant Magical Air', 'pages': '47'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Blind', 'pages': '52'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Bound Casting Tools', 'pages': '136'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Bound Magic', 'pages': '108'},
    {'flaw_type': 'Supernatural', 'book': 'The Cradle and the Crescent', magnitude: 'Major', points: 3, 'name': 'Bound Spells', 'pages': '31'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Bound to Magic', 'pages': '48'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Bound to (Role)', 'pages': '76'},
    {'flaw_type': 'Social', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Branded Criminal', 'pages': '52'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Broken Vessel', 'pages': '77'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Societates', magnitude: 'Minor', points: 1, 'name': 'Brutal Artist', 'pages': '56'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Bully', 'pages': '11'},
    {'flaw_type': 'Personality', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Bully [2]', 'pages': '11'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Busybody', 'pages': '52'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Carefree', 'pages': '52'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Careless Sorcerer', 'pages': '52'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Careless with (Ability)', 'pages': '77'},
    {'flaw_type': 'General', 'book': 'The Sundered Eagle: The Theban Tribunal', magnitude: 'Minor', points: 1, 'name': 'Castratus', 'pages': '38'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Chaotic Magic', 'pages': '52'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Charm Magician', 'pages': '83'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Close Family Ties', 'pages': '52'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Clumsy', 'pages': '52'},
    {'flaw_type': 'Supernatural', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Clumsy Magic', 'pages': '18'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Clumsy Magic [2]', 'pages': '52'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Compassionate', 'pages': '52'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Compassionate [2]', 'pages': '52'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Compulsion', 'pages': '52'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Major', points: 3, 'name': 'Compulsive Lying', 'pages': '78'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Compulsive Lying [2]', 'pages': '78'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Confraternity Member', 'pages': '136'},
    {'flaw_type': 'Hermetic', 'book': 'Legends of Hermes', magnitude: 'Major', points: 3, 'name': 'Constant Expression', 'pages': '16'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Consumed Casting Tools', 'pages': '136'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Continence', 'pages': '52'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Corrupted Abilities', 'pages': '87'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Corrupted Abilities [2]', 'pages': '87'},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Corrupted Arts', 'pages': '87-88 '},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Corrupted Arts [2]', 'pages': '87-88 '},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Corrupted Spells', 'pages': '88'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Corrupted Spells [2]', 'pages': '88'},
    {'flaw_type': 'Supernatural', 'book': 'Ancient Magic', magnitude: 'Minor', points: 1, 'name': 'Corrupt Fertility Ritual', 'pages': '59'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Covenant Upbringing', 'pages': '52'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Craving for Travel', 'pages': '78'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Creative Block', 'pages': '52'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Crippled', 'pages': '52'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Cursed Guile', 'pages': '78'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Curse of Slander', 'pages': '78'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Curse of Slander [2]', 'pages': '78'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Curse of Venus', 'pages': '52'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Cyclic Magic (negative)', 'pages': '52'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Dark Secret', 'pages': '52'},
    {'flaw_type': 'Story', 'book': 'The Church', magnitude: 'Major', points: 3, 'name': 'Dark Secret [2]', 'pages': '27'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Deaf', 'pages': '52'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Deficient Form', 'pages': '53'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Deficient Technique', 'pages': '53'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Deleterious Circumstances', 'pages': '53'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Delusion', 'pages': '53'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Demonic Familiar', 'pages': '88'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Dependence', 'pages': '11'},
    {'flaw_type': 'Personality', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Dependence [2]', 'pages': '11'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Dependent', 'pages': '53'},
    {'flaw_type': 'Personality', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Depraved', 'pages': '88'},
    {'flaw_type': 'Personality', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Depraved [2]', 'pages': '88'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Depressed', 'pages': '53'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Deteriorating Power', 'pages': '48'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Devoted Parent', 'pages': '79'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Divine', magnitude: 'Minor', points: 1, 'name': 'Dhimmi', 'pages': '115-116 '},
    {'flaw_type': 'General', 'book': 'The Cradle and the Crescent', magnitude: 'Minor', points: 1, 'name': 'Dhimmi [2]', 'pages': '15'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Diabolic Past', 'pages': '53'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Difficult Longevity Ritual', 'pages': '53'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Difficult Spontaneous Magic', 'pages': '53'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Difficult Underlings', 'pages': '53'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Disfigured', 'pages': '53'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Disjointed Magic', 'pages': '53'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Disorientating Magic', 'pages': '53'},
    {'flaw_type': 'Personality', 'book': 'Guardians of the Forests', magnitude: 'Minor', points: 1, 'name': 'Dispassionate', 'pages': '40'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Driven', 'pages': '53'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Driven [2]', 'pages': '53'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Dutybound', 'pages': '53'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Dwarf', 'pages': '53'},
    {'flaw_type': 'Story', 'book': 'City & Guild', magnitude: 'Minor', points: 1, 'name': 'Employed by Company', 'pages': '109'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Enemies', 'pages': '53'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Enfeebled', 'pages': '53'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Societates', magnitude: 'Minor', points: 1, 'name': 'Envied Beauty', 'pages': '56'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Envious', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Envious [2]', 'pages': '54'},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Environmental Magic Condition', 'pages': '48'},
    {'flaw_type': 'General', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Environmental Sensitivity', 'pages': '48'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Eremite', 'pages': '36'},
    {'flaw_type': 'General', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Essential Flaw', 'pages': '48'},
    {'flaw_type': 'General', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Essential Flaw [2]', 'pages': '48'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Divine', magnitude: 'Minor', points: 1, 'name': 'Eunuch', 'pages': '116'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Evil Destiny', 'pages': '88'},
    {'flaw_type': 'Hermetic', 'book': 'Magi of Hermes', magnitude: 'Minor', points: 1, 'name': 'Exciting Experimentation', 'pages': '26'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Excommunicate', 'pages': '93'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Exiled Atlantian', 'pages': '48'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Faerie', magnitude: 'Major', points: 3, 'name': 'Faerie Antipathy', 'pages': '114'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Faerie', magnitude: 'Minor', points: 1, 'name': 'Faerie Antipathy [2]', 'pages': '114'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Faerie Friend', 'pages': '54'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: Faerie', magnitude: 'Major', points: 3, 'name': 'Faerie Heritage', 'pages': '114'},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: Faerie', magnitude: 'Minor', points: 1, 'name': 'Faerie Metamorphosis', 'pages': '114'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Faerie', magnitude: 'Minor', points: 1, 'name': 'Faerie Metamorphosis [2]', 'pages': '114'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Faerie Upbringing', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Realms of Power: Faerie', magnitude: 'Minor', points: 1, 'name': 'Faerie Upbringing [2]', 'pages': '115'},
    {'flaw_type': 'Social', 'book': 'City & Guild', magnitude: 'Minor', points: 1, 'name': 'Failed Journeyman', 'pages': '52'},
    {'flaw_type': 'Social', 'book': 'City & Guild', magnitude: 'Minor', points: 1, 'name': 'Failed Master', 'pages': '52'},
    {'flaw_type': 'Social', 'book': 'Realms of Power: The Divine', magnitude: 'Minor', points: 1, 'name': 'Failed Monk/Nun', 'pages': '93'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'False Power', 'pages': '88-89'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'False Power [2]', 'pages': '88-89 '},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Favors', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Fear', 'pages': '54'},
    {'flaw_type': 'General', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Feral Scent', 'pages': '38'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Feral Upbringing', 'pages': '54'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Fettered Magic', 'pages': '108'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Feud', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Art & Academe', magnitude: 'Minor', points: 1, 'name': 'Fickle Nature', 'pages': '134'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Fish Out of Water (Terrain)', 'pages': '80'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Flashbacks', 'pages': '79'},
    {'flaw_type': 'Hermetic', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Flawed Folk Witch Gift Opening', 'pages': '34'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Flawed Parma Magica', 'pages': '54'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Societates', magnitude: 'Minor', points: 1, 'name': 'Flawed Powers', 'pages': '107'},
    {'flaw_type': 'Supernatural', 'book': 'Art & Academe', magnitude: 'Minor', points: 1, 'name': 'Fluctuating Fortune', 'pages': '134'},
    {'flaw_type': 'Personality', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Follower/Pack Mentality', 'pages': '38'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Foreign Upbringing', 'pages': '80'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': '(Form) Monstrosity', 'pages': '48-49 '},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Fostered Apprentice', 'pages': '26'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Fragile Constitution', 'pages': '54'},
    {'flaw_type': 'General', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Frail', 'pages': '12'},
    {'flaw_type': 'Supernatural', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Frail Magic', 'pages': '19'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Minor', points: 1, 'name': 'Friendly Mistress', 'pages': '19'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Fury', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Generous', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Generous [2]', 'pages': '54'},
    {'flaw_type': 'Hermetic', 'book': 'Guardians of the Forests: The Rhine Tribunal', magnitude: 'Minor', points: 1, 'name': '(Gild) Emnity (Rhine)', 'pages': '20'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: Faerie', magnitude: 'Major', points: 3, 'name': 'Greater Charm', 'pages': '115'},
    {'flaw_type': 'Supernatural', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Greater Malediction', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Greedy', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Greedy [2]', 'pages': '54'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Grudge', 'pages': '136'},
    {'flaw_type': 'Personality', 'book': 'Art & Academe', magnitude: 'Minor', points: 1, 'name': 'Gullible', 'pages': '134'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Gullible [2]', 'pages': '80'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Hallucinations', 'pages': '80'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Harmless Magic', 'pages': '87'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Harsh Moon', 'pages': '35'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Hatred', 'pages': '54'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Hatred [2]', 'pages': '54'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Hedge Wizard', 'pages': '54'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Heir', 'pages': '54'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Hermetic Patron', 'pages': '108'},
    {'flaw_type': 'Heroic', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Heroic Personality', 'pages': '108-109 '},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Higher Purpose', 'pages': '54'},
    {'flaw_type': 'General', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Hobbled', 'pages': '136'},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: Faerie', magnitude: 'Major', points: 3, 'name': 'Homunculus Wizard', 'pages': '115'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: Faerie', magnitude: 'Major', points: 3, 'name': 'Homunculus Wizard [2]', 'pages': '115'},
    {'flaw_type': 'Supernatural', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Horrifying Appearance', 'pages': '83'},
    {'flaw_type': 'Supernatural', 'book': 'The Sundered Eagle: The Theban Tribunal', magnitude: 'Major', points: 3, 'name': 'Horrifying Appearance [2]', 'pages': '120'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Humble', 'pages': '54'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Hunchback', 'pages': '55'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Hunger for (Form) Magic', 'pages': '49'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Illegitimate Lineage', 'pages': '109'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Imaginary Folk Tradition Vulnerability', 'pages': '80'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Impious Friend', 'pages': '89'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Impious Friend [2]', 'pages': '89'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Incompatible Arts', 'pages': '55'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Incompatible Hedge Arts', 'pages': '58, 83 '},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Incomprehensible', 'pages': '55'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Inconstant Magic', 'pages': '87'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Independent Craftsman', 'pages': '81'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Indiscreet', 'pages': '55'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Infamous', 'pages': '55'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Infamous Master', 'pages': '55'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Infatuation', 'pages': '11'},
    {'flaw_type': 'Story', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Infatuation [2]', 'pages': '11'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Infatuation [3]', 'pages': '11'},
    {'flaw_type': 'Story', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Infatuation [4]', 'pages': '11'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Inflexible Magic', 'pages': '58'},
    {'flaw_type': 'Supernatural', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Inscribed Shadow', 'pages': '73'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Intervention Prone', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Jinxed', 'pages': '81'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Judged Unfairly', 'pages': '55'},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Karaite Magic', 'pages': '137'},
    {'flaw_type': 'Story', 'book': 'Lords of Men', magnitude: 'Major', points: 3, 'name': 'Knightly Demands', 'pages': '31'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Know-It-All', 'pages': '11'},
    {'flaw_type': 'Personality', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Know-It-All [2]', 'pages': '11'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Know-It-All [3]', 'pages': '11'},
    {'flaw_type': 'Personality', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Know-It-All [4]', 'pages': '11'},
    {'flaw_type': 'Story', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Known Hedge Wizard', 'pages': '12'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Known Wizard', 'pages': '12'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Laboratory Magician', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Lame', 'pages': '55'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Late Bloomer', 'pages': '12'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Lecherous', 'pages': '55'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Lecherous [2]', 'pages': '55'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Legacy', 'pages': '109'},
    {'flaw_type': 'General', 'book': 'Houses of Hermes: Societates', magnitude: 'Major', points: 3, 'name': 'Leprosy', 'pages': '94'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Faerie', magnitude: 'Minor', points: 1, 'name': 'Lesser Charm', 'pages': '115'},
    {'flaw_type': 'Supernatural', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Lesser Malediction', 'pages': '55'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Limited Magic Resistance', 'pages': '55'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Lingering Injury', 'pages': '81'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Loose Magic', 'pages': '55'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Lost Love', 'pages': '55'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Low Self-Esteem', 'pages': '55'},
    {'flaw_type': 'General', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Low Tolerance', 'pages': '13'},
    {'flaw_type': 'Supernatural', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Lycanthrope', 'pages': '55'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Magical Air', 'pages': '56'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Magical Animal Companion', 'pages': '56, RM 18'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Magical (Being) Companion', 'pages': '49'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Magical Fascination', 'pages': '81'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Magic Addiction', 'pages': '56'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Minor', points: 1, 'name': 'Magic Aura Temple', 'pages': '19'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Major Magical Deficiency', 'pages': '122'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Malignant Magus', 'pages': '73'},
    {'flaw_type': 'Supernatural', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Malignant Magus [2]', 'pages': '73'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Manifest Sin', 'pages': '81'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Manufactured Ignorance', 'pages': '89'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Manufactured Ignorance [2]', 'pages': '89'},
    {'flaw_type': 'Story', 'book': 'City & Guild', magnitude: 'Major', points: 3, 'name': 'Many Marriageable Daughters', 'pages': '109'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Master of None', 'pages': '81'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Meddler', 'pages': '56'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Meddler [2]', 'pages': '56'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Mentor', 'pages': '56'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Societates', magnitude: 'Minor', points: 1, 'name': 'Miles', 'pages': '31'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Minor Animal Companion', 'pages': '51'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Minor Magical Deficiency', 'pages': '123'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Missing Ear', 'pages': '56'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Missing Eye', 'pages': '56'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Missing Hand', 'pages': '56'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Mistaken Identity', 'pages': '56'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Monastic Vows', 'pages': '56'},
    {'flaw_type': 'Hermetic', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Monastic Vows (Hermetic) ', 'pages': '93'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Monstrous Blood', 'pages': '49-50 '},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Motion Sickness', 'pages': '56'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Mute', 'pages': '56'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Natt Thel Prone', 'pages': '123'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Necessary Condition', 'pages': '56'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Necessary (Realm) Aura for (Ability) ', 'pages': '82'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Night Terrors', 'pages': '82'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Nocturnal', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Noncombatant', 'pages': '56'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Divine', magnitude: 'Minor', points: 1, 'name': 'Non-traditional', 'pages': '36'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'No Chartae Making', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'No Hands', 'pages': '56'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'No Magical Defenses', 'pages': '12, RM 12 '},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'No Sense of Direction', 'pages': '56'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'No Tattoo Magic', 'pages': '57'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'No Text Casting', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'No Tradition', 'pages': '89'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Oath of Fealty', 'pages': '56-57'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Obese', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Obsessed', 'pages': '57'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Offensive to Animals', 'pages': '57'},
    {'flaw_type': 'Supernatural', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Offensive to Animals [2]', 'pages': '57'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Offensive to (Beings)', 'pages': '87'},
    {'flaw_type': 'Supernatural', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Offensive to (Beings) [2]', 'pages': '87'},
    {'flaw_type': 'General', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Offensive to (Beings) [3]', 'pages': '50'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Optimistic', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Optimistic [2]', 'pages': '57'},
    {'flaw_type': 'Social', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Outcast', 'pages': '57'},
    {'flaw_type': 'Social', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Outlaw', 'pages': '57'},
    {'flaw_type': 'Social', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Outlaw Leader', 'pages': '57'},
    {'flaw_type': 'Social', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Outsider', 'pages': '57'},
    {'flaw_type': 'Social', 'book': 'Realms of Power: The Divine', magnitude: 'Minor', points: 1, 'name': 'Outsider (Minor)', 'pages': '137'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Overconfident', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Overconfident [2]', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Oversensitive', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Pack Mentality/Follower', 'pages': '38'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Pack Mentality/Follower [2]', 'pages': '82'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Major', points: 3, 'name': 'Pagan', 'pages': '109'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Pagan [2]', 'pages': '93'},
    {'flaw_type': 'Story', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Pagan [3]', 'pages': '12'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Pagan [4]', 'pages': '12'},
    {'flaw_type': 'Story', 'book': 'Grogs', magnitude: 'Major', points: 3, 'name': 'Pagan [5]', 'pages': '82'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Painful Magic', 'pages': '57'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Palsied Hands', 'pages': '57'},
    {'flaw_type': 'Story', 'book': 'The Cradle and the Crescent', magnitude: 'Major', points: 3, 'name': 'Patron', 'pages': '31'},
    {'flaw_type': 'Story', 'book': 'The Cradle and the Crescent', magnitude: 'Minor', points: 1, 'name': 'Patron [2]', 'pages': '31'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Pessimistic', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Pious', 'pages': '58'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Pious [2]', 'pages': '58'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Plagued by Supernatural Entity', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Poor', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Poorly Trained Folk Witch', 'pages': '35'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Poorly Trained Gruagach', 'pages': '58'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Poorly Trained Magician', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Poor (Characteristic)', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Poor Concentration', 'pages': '50'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Poor Eyesight', 'pages': '58'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Poor Formulaic Magic', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Poor Hearing', 'pages': '58'},
    {'flaw_type': 'Supernatural', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Poor Incantation Magic', 'pages': '18'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Poor Living Conditions', 'pages': '83'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Poor Memory', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Poor Student', 'pages': '58'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Predictive Stigmata', 'pages': '73'},
    {'flaw_type': 'Supernatural', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Predictive Stigmata [2]', 'pages': '73'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Primitive Equipment', 'pages': '83'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Primitive Tradition', 'pages': '35'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Primogeniture Lineage', 'pages': '136'},
    {'flaw_type': 'Story', 'book': 'Art & Academe', magnitude: 'Major', points: 3, 'name': 'Proctor/Rector', 'pages': '92'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Prohibition', 'pages': '58'},
    {'flaw_type': 'Story', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Prolonged Apprenticeship', 'pages': '19-20 '},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Proud', 'pages': '58'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Proud [2]', 'pages': '58'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Raised from the Dead', 'pages': '36'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Raised from the Dead [2]', 'pages': '36'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Raised in the Gutter', 'pages': '83'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Rarefied Tradition', 'pages': '35'},
    {'flaw_type': 'Story', 'book': 'The Cradle and the Crescent', magnitude: 'Major', points: 3, 'name': ' (Realm) Spirit Companion', 'pages': '31'},
    {'flaw_type': 'Story', 'book': 'The Cradle and the Crescent', magnitude: 'Minor', points: 1, 'name': '(Realm) Spirit Companion [2]', 'pages': '31'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': '(Realm) Stigmatic', 'pages': '83'},
    {'flaw_type': 'Personality', 'book': 'The Sundered Eagle: The Theban Tribunal', magnitude: 'Major', points: 3, 'name': 'Rebellious', 'pages': '120'},
    {'flaw_type': 'Personality', 'book': 'The Cradle and the Crescent', magnitude: 'Major', points: 3, 'name': 'Rebellious [2]', 'pages': '144'},
    {'flaw_type': 'Personality', 'book': 'The Sundered Eagle: The Theban Tribunal', magnitude: 'Minor', points: 1, 'name': 'Rebellious [3]', 'pages': '120'},
    {'flaw_type': 'Personality', 'book': 'The Cradle and the Crescent', magnitude: 'Minor', points: 1, 'name': 'Rebellious [4]', 'pages': '144'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Reckless', 'pages': '58'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Reclusive', 'pages': '58'},
    {'flaw_type': 'Story', 'book': 'Art & Academe', magnitude: 'Major', points: 3, 'name': 'Rector/Proctor', 'pages': '92'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Repellent', 'pages': '89'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Repellent [2]', 'pages': '89'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Restricted Learning', 'pages': '83'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Restricted Power', 'pages': '50'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Restriction', 'pages': '58'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Rigid Magic', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Rolling Stone', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Savantism', 'pages': '84'},
    {'flaw_type': 'Personality', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Secretive', 'pages': '38'},
    {'flaw_type': 'Personality', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Seeker', 'pages': '25'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Servant of the (Land)', 'pages': '50'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Sheltered Upbringing', 'pages': '59'},
    {'flaw_type': 'Supernatural', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Short-Lived Magic', 'pages': '18'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Short-Lived Magic [2]', 'pages': '59'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Short-Lived Runes', 'pages': '123'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Short-Ranged Curses', 'pages': '35'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Short-Ranged Magic', 'pages': '59'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Short Attention Span', 'pages': '58'},
    {'flaw_type': 'General', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Short of Breath', 'pages': '13'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Silent Tradition', 'pages': '35'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Simple-Minded', 'pages': '59'},
    {'flaw_type': 'Social', 'book': 'Guardians of the Forests', magnitude: 'Major', points: 3, 'name': 'Slave', 'pages': '102'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Sleep Disorder', 'pages': '84'},
    {'flaw_type': 'Personality', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Slothful', 'pages': '38'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Slow Caster', 'pages': '59'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Slow Caster [2]', 'pages': '123'},
    {'flaw_type': 'Supernatural', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Slow Power', 'pages': '50'},
    {'flaw_type': 'General', 'book': 'Apprentices', magnitude: 'Minor', points: 1, 'name': 'Slow Reflexes', 'pages': '13'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Small Frame', 'pages': '59'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Social Handicap', 'pages': '59'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Soft-Hearted', 'pages': '59'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Spontaneous Casting Tools', 'pages': '136'},
    {'flaw_type': 'Supernatural', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Stigmatic Catalyst', 'pages': '73'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Stockade Parma Magica', 'pages': '25'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Stuck in His Ways', 'pages': '84'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Study Requirement', 'pages': '59'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Supernatural Nuisance', 'pages': '59'},
    {'flaw_type': 'Hermetic', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Suppressed Gift', 'pages': '13'},
    {'flaw_type': 'Story', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Suppressed Gift [2]', 'pages': '13'},
    {'flaw_type': 'Social', 'book': 'Art & Academe', magnitude: 'Minor', points: 1, 'name': 'Surgical Empiricus', 'pages': '56'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Susceptibility to Divine Power', 'pages': '59'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Susceptibility to Faerie Power', 'pages': '59'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Susceptibility to Infernal Power', 'pages': '59'},
    {'flaw_type': 'Supernatural', 'book': 'Magi of Hermes', magnitude: 'Minor', points: 1, 'name': 'Susceptibility to Sunlight', 'pages': '128'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Susceptible to Warping', 'pages': '84'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Tainted Offspring', 'pages': '89-90'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Tainted Offspring [2]', 'pages': '89-90 '},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Tainted with Evil', 'pages': '59'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Temperate', 'pages': '59'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Major', points: 3, 'name': 'The Falling Evil', 'pages': '79'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Tormenting Master', 'pages': '59'},
    {'flaw_type': 'Heroic', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Tragic (Characteristic)', 'pages': '109'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Tragic Life', 'pages': '90'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Transformation Prone', 'pages': '57'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Transvestite', 'pages': '59'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'True Love (NPC)', 'pages': '59-60'},
    {'flaw_type': 'Child', 'book': 'Apprentices', magnitude: 'Major', points: 3, 'name': 'Turbulence Prone', 'pages': '12'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Twilight Prone', 'pages': '60'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Divine', magnitude: 'Major', points: 3, 'name': 'Unbaptized', 'pages': '93'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Unbearable to (Beings)', 'pages': '87'},
    {'flaw_type': 'Supernatural', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Minor', points: 1, 'name': 'Unbearable to (Beings) [2]', 'pages': '87'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Uncertain Faith', 'pages': '84'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Uncontrollable Strength', 'pages': '85'},
    {'flaw_type': 'Story', 'book': 'City & Guild', magnitude: 'Major', points: 3, 'name': 'Unhappily Married', 'pages': '109'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Unimaginative Learner', 'pages': '60'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Uninspirational', 'pages': '85'},
    {'flaw_type': 'Story', 'book': 'Art & Academe', magnitude: 'Major', points: 3, 'name': 'University Dean', 'pages': '92'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Unlucky', 'pages': '85'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Major', points: 3, 'name': 'Unnatural Magic', 'pages': '87'},
    {'flaw_type': 'Supernatural', 'book': 'Rival Magic', magnitude: 'Major', points: 3, 'name': 'Unpredictable Magic', 'pages': '18'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Unpredictable Magic [2]', 'pages': '60'},
    {'flaw_type': 'Supernatural', 'book': 'Art & Academe', magnitude: 'Minor', points: 1, 'name': 'Unruly Air', 'pages': '134'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Unspecialized', 'pages': '85'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Unstable Magic', 'pages': '35'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Unstructured Caster', 'pages': '60'},
    {'flaw_type': 'Social', 'book': 'Houses of Hermes: True Lineages', magnitude: 'Minor', points: 1, 'name': 'Usurer', 'pages': '109'},
    {'flaw_type': 'Story', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Major', points: 3, 'name': 'Vendetta', 'pages': '136'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Vengeful Powers', 'pages': '90'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Major', points: 3, 'name': 'Vengeful Powers [2]', 'pages': '90'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Viaticarus', 'pages': '85'},
    {'flaw_type': 'Story', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Visions', 'pages': '60'},
    {'flaw_type': 'Supernatural', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Visions [2]', 'pages': '60'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Vow', 'pages': '60'},
    {'flaw_type': 'Hermetic', 'book': 'The Mysteries, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Vulnerable Casting', 'pages': '38'},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Mystery Cults', magnitude: 'Major', points: 3, 'name': 'Vulnerable Magic', 'pages': '87-88 '},
    {'flaw_type': 'Hermetic', 'book': 'Houses of Hermes: Societates', magnitude: 'Minor', points: 1, 'name': 'Vulnerable to Folk Tradition', 'pages': '107'},
    {'flaw_type': 'Hermetic', 'book': 'The Cradle and the Crescent', magnitude: 'Minor', points: 1, 'name': 'Vulnerable to Folk Tradition (Islamic)', 'pages': '80'},
    {'flaw_type': 'Hermetic', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Vulnerable to (Form)', 'pages': '20'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Vulnerable to (Form) [2]', 'pages': '20'},
    {'flaw_type': 'Story', 'book': 'Realms of Power: Magic', magnitude: 'Major', points: 3, 'name': 'Wanderlust', 'pages': '50'},
    {'flaw_type': 'Supernatural', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Warped by Magic', 'pages': '85'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Warped Magic', 'pages': '60'},
    {'flaw_type': 'Personality', 'book': 'Realms of Power: Magic', magnitude: 'Minor', points: 1, 'name': 'Warped Senses', 'pages': '50-51 '},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Waster of Vis', 'pages': '61'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weakness', 'pages': '61'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weak-Willed', 'pages': '61'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Amulets', 'pages': '83'},
    {'flaw_type': 'General', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Characteristics', 'pages': '61'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Chartae', 'pages': '83'},
    {'flaw_type': 'Hermetic', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Weak Elemental Resistance', 'pages': '20'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Weak Elemental Resistance [2]', 'pages': '20'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Enchanter', 'pages': '61'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Magic', 'pages': '61'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Weak Magic Resistance', 'pages': '61'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Parens', 'pages': '61'},
    {'flaw_type': 'Personality', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Weak Personality', 'pages': '85'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Scholar', 'pages': '61'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Weak Spontaneous Magic', 'pages': '61'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Minor', points: 1, 'name': 'Weak Tattoo Magic', 'pages': '58'},
    {'flaw_type': 'Supernatural', 'book': 'Hedge Magic, Revised Edition', magnitude: 'Major', points: 3, 'name': 'Weak Verbal Charms', 'pages': '82'},
    {'flaw_type': 'Hermetic', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Weird Magic', 'pages': '61'},
    {'flaw_type': 'Tainted', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Witch Marks', 'pages': '90'},
    {'flaw_type': 'General', 'book': 'Realms of Power: The Infernal', magnitude: 'Minor', points: 1, 'name': 'Witch Marks [2]', 'pages': '90'},
    {'flaw_type': 'General', 'book': 'Grogs', magnitude: 'Minor', points: 1, 'name': 'Worthless Abilities', 'pages': '86'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Major', points: 3, 'name': 'Wrathful', 'pages': '61'},
    {'flaw_type': 'Personality', 'book': 'Ars Magica, Fifth Edition', magnitude: 'Minor', points: 1, 'name': 'Wrathful [2]', 'pages': '61'}
];
